### ISSUE TITLE
org.eclipse.Sdk from eclipse-nightly hangs on installing plugins

### ISSUE THREAD

**Issue by rgrunber** [mbooth101/eclipse-flatpak#3]
1) `$ flatpak run org.eclipse.Sdk` and select a new workspace
2) Help -> Install New Software...
3) Select "All Available Sites", filter for 'git' and install 'Git integration for Eclipse'
4) Hit next through the install details / license review, accept the license and click Finish

I seem to recall this wasn't an issue when I tried the Oxygen.1 runtime.

**Comment by mbooth101** [comment]
This should be fixed in the latest available flatpak from http://eclipse.matbooth.co.uk/flatpak/
