### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by vogella** [mbooth101/eclipse-flatpak#7]
I'm following the installation instructions from http://eclipse.matbooth.co.uk/flatpak/ but installation fails for me.

```
vogella@spike:~$ flatpak install eclipse-nightly org.eclipse.Sdk
Required runtime for org.eclipse.Sdk/x86_64/Photon (org.gnome.Platform/x86_64/3.28) is not installed, searching...
The required runtime org.gnome.Platform/x86_64/3.28 was not found in a configured remote.
error: The Application org.eclipse.Sdk/x86_64/Photon requires the runtime org.gnome.Platform/x86_64/3.28 which is not installed
````

**Comment by vogella** [comment]
Output of the remote-ls command:

```
vogella@spike:~$ flatpak remote-ls eclipse-nightly
org.eclipse.Platform      
org.eclipse.Platform.Debug
org.eclipse.Sdk           
org.eclipse.Sdk.Debug   
```

**Comment by akurtakov** [comment]
Can you follow the instructions from evolution https://wiki.gnome.org/Apps/Evolution/Flatpak#Install_prerequisites and changing to 3.28 version to continue?
Mat, can we automate this one or at least document it properly?

**Comment by vogella** [comment]
Looks better. Installation is now successful.

Can you add to the instructions where I find the IDE? After the process finishes I have no idea where to look.

**Comment by mbooth101** [comment]
Hmm, looks like only the flatpakref files specify the runtime location. I'll if adding the same to the repo file works or otherwise document it.

**Comment by akurtakov** [comment]
Lars, do you still face issue installing it ?

**Comment by vogella** [comment]
> Lars, do you still face issue installing it ?

Yes.

vogella@spike:~/temp$ flatpak install eclipse-nightly org.eclipse.Sdk
error: The Application org.eclipse.Sdk/x86_64/master requires the org.gnome.Platform/x86_64/3.30 which was not found

**Comment by akurtakov** [comment]
Mat, can you please add flatpakref on your page for installing the runtime? This will make it 2 steps but at least they will be fully automated.

**Comment by mbooth101** [comment]
The first sentence on the site contains a link to the Flatpak quick setup guide which shows you how to install Flatpak and configure the Flathub repository for your preferred distro...

This step is not optional ;-)

I can duplicate the instructions here, if you wish

**Comment by akurtakov** [comment]
Still if we can have a single install runtime button - it would make things simpler :)
