### ISSUE TITLE
Can eclipse flatpak be somehow linked to org.freedesktop.Sdk?

### ISSUE THREAD

**Issue by juxi500** [mbooth101/eclipse-flatpak#8]
Hello, I wanted to try to write a small c++ program in Eclipse flatpak, but I can't compile it, since Eclipse can't find gcc compiler. I have gcc compiler installed inside org.freedesktop.Sdk and it works fine with Codeblocks flatpak. Is it somehow possible to allow Eclipse flatpak to use org.freedesktop.Sdk binaries (including gcc)?

**Comment by mbooth101** [comment]
This should be fixed for a long time now, closing
