### ISSUE TITLE
Hovering over any java source element causes WebKitWebProcess crash

### ISSUE THREAD

**Issue by rgrunber** [mbooth101/eclipse-flatpak#9]
Fedora release 28 (Twenty Eight)
Eclipse SDK
Version: 2018-12 (4.10)
Build id: I20181010-0600

The executable seems to be /usr/libexec/webkit2gtk-4.0/WebKitWebProcess . I also recall running into this prior to updating to the 2018-12 flatpak.

Hovering over the element does bring up the shell, but the content isn't populated.

**Comment by mbooth101** [comment]
Yep, I noticed this too. I also observe the following in the that may be related:

```
SWT WebkitGDBus.java: Lost GDBus name. This should never occur

** (WebKitWebProcess:93): ERROR **: 14:23:09.323: SWT web extension: Call failed because 'GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnk
nown.'
```

**Comment by ericwill** [comment]
> ```
> SWT WebkitGDBus.java: Lost GDBus name. This should never occur
> 
> ** (WebKitWebProcess:93): ERROR **: 14:23:09.323: SWT web extension: Call failed because 'GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnk
> nown.'
> ```

So SWT's Webkit2 implementation works by having a main SWT webkit instance, and a separate process called a webextension. The webextension handles stuff like JavaScript, so its created as soon as that sort of content is dealt with by the main SWT webkit instance.

The SWT webkit instance runs a DBus server. Upon creation of the webextension process, SWT will pass its (SWT's) DBus server name to the extension. The extension will initialize, and then "phone home" to SWT via the DBus information it was supplied. This is the part that is breaking, i.e. the extension can't reach the SWT DBus server at the address/name it was given, so the extension is crashing.

My guess is that the SWT DBus/Webkit instance is killed somewhere between extension creation and initialization. Why this only happens in flatpak is a bit of a mystery...

**Comment by akurtakov** [comment]
IMHO it's flatpak sandboxing breaking the dbus. Mat, in case you haven't open dbus entirely (--socket=session-bus) please do so for now.

**Comment by mbooth101** [comment]
By default Flatpak routes dbus through a filtering proxy and I was only allowing calls through the filter to specific dbus interfaces that Eclipse needed:

* org.freedesktop.Flatpak -- For launching processes on the sandbox host
* org.freedesktop.secrets -- For gnome keyring integration

If SWT if _providing_ a dbus interface, then AIUI the sandbox by default is only allowed to own its own app id, and sub-names on the bus, i.e. "org.eclipse.Sdk" or "org.eclipse.Platform" for the two Flatpaks that are built currently.

This means that we likely need a way to set the name of the interface that SWT is providing on a per-Flatpak basis; having SWT interrogate an environment variable might be the most convenient way to do this.

**Comment by ericwill** [comment]
> If SWT if _providing_ a dbus interface, then AIUI the sandbox by default is only allowed to own its own app id, and sub-names on the bus, i.e. "org.eclipse.Sdk" or "org.eclipse.Platform" for the two Flatpaks that are built currently.
> 
> This means that we likely need a way to set the name of the interface that SWT is providing on a per-Flatpak basis; having SWT interrogate an environment variable might be the most convenient way to do this.

I think this is definitely doable.

**Comment by mbooth101** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=540060

**Comment by mbooth101** [comment]
This is worked around downstream by granting access to the whole session bus, for details of upstream work, please follow this bug: 

> https://bugs.eclipse.org/bugs/show_bug.cgi?id=540060
